# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir G:/.shortcut-targets-by-id/18l05k5DVoB5pVKzFoiXH5izoP1FLnSFh/Project_group15/Calculator/Calculator.cache/wt [current_project]
set_property parent.project_path G:/.shortcut-targets-by-id/18l05k5DVoB5pVKzFoiXH5izoP1FLnSFh/Project_group15/Calculator/Calculator.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo g:/.shortcut-targets-by-id/18l05k5DVoB5pVKzFoiXH5izoP1FLnSFh/Project_group15/Calculator/Calculator.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  G:/.shortcut-targets-by-id/18l05k5DVoB5pVKzFoiXH5izoP1FLnSFh/Project_group15/Calculator/Calculator.srcs/sources_1/imports/Project_group15/uart_final/uart_final.srcs/sources_1/imports/new/SerialRX.vhd
  G:/.shortcut-targets-by-id/18l05k5DVoB5pVKzFoiXH5izoP1FLnSFh/Project_group15/Calculator/Calculator.srcs/sources_1/imports/Project_group15/Datapath_M/Datapath_M.srcs/sources_1/imports/new/add_controller.vhd
  G:/.shortcut-targets-by-id/18l05k5DVoB5pVKzFoiXH5izoP1FLnSFh/Project_group15/Calculator/Calculator.srcs/sources_1/imports/new/bin2bcd.vhd
  G:/.shortcut-targets-by-id/18l05k5DVoB5pVKzFoiXH5izoP1FLnSFh/Project_group15/Calculator/Calculator.srcs/sources_1/imports/Project_group15/Datapath_M/Datapath_M.srcs/sources_1/imports/new/datapath.vhd
  G:/.shortcut-targets-by-id/18l05k5DVoB5pVKzFoiXH5izoP1FLnSFh/Project_group15/Calculator/Calculator.srcs/sources_1/imports/Project_group15/uart_final/uart_final.srcs/sources_1/imports/CS56_ES31_Lab4_20X_files/mux7seg.vhd
  G:/.shortcut-targets-by-id/18l05k5DVoB5pVKzFoiXH5izoP1FLnSFh/Project_group15/Calculator/Calculator.srcs/sources_1/imports/Project_group15/uart_final/uart_final.srcs/sources_1/imports/Old_Lab5/lab5top.vhd
}
read_ip -quiet G:/.shortcut-targets-by-id/18l05k5DVoB5pVKzFoiXH5izoP1FLnSFh/Project_group15/Calculator/Calculator.srcs/sources_1/ip/div_gen_0_1/div_gen_0.xci
set_property used_in_implementation false [get_files -all g:/.shortcut-targets-by-id/18l05k5DVoB5pVKzFoiXH5izoP1FLnSFh/Project_group15/Calculator/Calculator.srcs/sources_1/ip/div_gen_0_1/div_gen_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc G:/.shortcut-targets-by-id/18l05k5DVoB5pVKzFoiXH5izoP1FLnSFh/Project_group15/Calculator/Calculator.srcs/constrs_1/imports/CS56/Basys3_Master.xdc
set_property used_in_implementation false [get_files G:/.shortcut-targets-by-id/18l05k5DVoB5pVKzFoiXH5izoP1FLnSFh/Project_group15/Calculator/Calculator.srcs/constrs_1/imports/CS56/Basys3_Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top lab5top -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef lab5top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file lab5top_utilization_synth.rpt -pb lab5top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
