webtalk_init -webtalk_dir E:/My Drive/Project_group15/Calculator/Calculator.sim/sim_1/behav/xsim/xsim.dir/SerialRx_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Sep  1 18:14:18 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2489853" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210643936_1777485687_0_121" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "521771da-1840-4760-a5b0-a7f1f28fac5e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "22c6dd2f7e5f4a03acd0c362c6c9ad2a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "351" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows Server 2012 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2095 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "33" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "509 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "75 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "1142" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "383" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "4.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "163288_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3365323871 -regid "210643936_1777485687_0_121" -xml E:/My Drive/Project_group15/Calculator/Calculator.sim/sim_1/behav/xsim/xsim.dir/SerialRx_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/My Drive/Project_group15/Calculator/Calculator.sim/sim_1/behav/xsim/xsim.dir/SerialRx_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/My Drive/Project_group15/Calculator/Calculator.sim/sim_1/behav/xsim/xsim.dir/SerialRx_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
