webtalk_init -webtalk_dir C:/Users/f003mg3/Divisiontest/Divisiontest.sim/sim_1/behav/xsim/xsim.dir/divetest_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Aug 31 18:29:22 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2489853" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210643936_1777485687_0_121" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "521771da-1840-4760-a5b0-a7f1f28fac5e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "42d96641743c4c90beb0e24e2d91f7dd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows Server 2012 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2095 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "50001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.72_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "16260_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4241829517 -regid "210643936_1777485687_0_121" -xml C:/Users/f003mg3/Divisiontest/Divisiontest.sim/sim_1/behav/xsim/xsim.dir/divetest_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/f003mg3/Divisiontest/Divisiontest.sim/sim_1/behav/xsim/xsim.dir/divetest_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/f003mg3/Divisiontest/Divisiontest.sim/sim_1/behav/xsim/xsim.dir/divetest_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
